language: scala

scala:
  - 2.12.3

jdk:
  - oraclejdk8

before_script:
  - sbt 'project tictactoe' run < /dev/null > /dev/null 2>&1 & SERVER_PID=$!

script:
  - sbt test

after_script:
  - kill $SERVER_PID